<?php
// Generated by Zend Framework 2
return array(
    'Cathedral\Module'                                     => __DIR__ . '/Module.php',
    'Cathedral\Builder\BuilderAbstract'                    => __DIR__ . '/src/Cathedral/Builder/BuilderAbstract.php',
    'Cathedral\Builder\BuilderInterface'                   => __DIR__ . '/src/Cathedral/Builder/BuilderInterface.php',
    'Cathedral\Builder\BuilderManager'                     => __DIR__ . '/src/Cathedral/Builder/BuilderManager.php',
    'Cathedral\Builder\DataTableBuilder'                   => __DIR__ . '/src/Cathedral/Builder/DataTableBuilder.php',
    'Cathedral\Builder\EntityAbstractBuilder'              => __DIR__ . '/src/Cathedral/Builder/EntityAbstractBuilder.php',
    'Cathedral\Builder\EntityBuilder'                      => __DIR__ . '/src/Cathedral/Builder/EntityBuilder.php',
    'Cathedral\Builder\Exception\ConfigurationException'   => __DIR__ . '/src/Cathedral/Builder/Exception/ConfigurationException.php',
    'Cathedral\Builder\Exception\ErrorException'           => __DIR__ . '/src/Cathedral/Builder/Exception/ErrorException.php',
    'Cathedral\Builder\Exception\ExceptionInterface'       => __DIR__ . '/src/Cathedral/Builder/Exception/ExceptionInterface.php',
    'Cathedral\Builder\Exception\InvalidArgumentException' => __DIR__ . '/src/Cathedral/Builder/Exception/InvalidArgumentException.php',
    'Cathedral\Builder\Exception\PermissionException'      => __DIR__ . '/src/Cathedral/Builder/Exception/PermissionException.php',
    'Cathedral\Builder\Exception\RuntimeException'         => __DIR__ . '/src/Cathedral/Builder/Exception/RuntimeException.php',
    'Cathedral\Builder\Exception\UnexpectedValueException' => __DIR__ . '/src/Cathedral/Builder/Exception/UnexpectedValueException.php',
    'Cathedral\Builder\NameManager'                        => __DIR__ . '/src/Cathedral/Builder/NameManager.php',
    'Cathedral\Builder\Version'                            => __DIR__ . '/src/Cathedral/Builder/Version.php',
    'Cathedral\Controller\BasicUIController'               => __DIR__ . '/src/Cathedral/Controller/BasicUIController.php',
    'Cathedral\Controller\BuilderToolController'           => __DIR__ . '/src/Cathedral/Controller/BuilderToolController.php',
    'CathedralTest\Bootstrap'                              => __DIR__ . '/test/Bootstrap.php',
    'CathedralTest\Controller\BasicUIControllerTest'       => __DIR__ . '/test/CathedralTest/Controller/BasicUIControllerTest.php',
);