<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'cathedral/builder-web/build' => __DIR__ . '/view/cathedral/builder-web/build.phtml',
    'cathedral/builder-web/index' => __DIR__ . '/view/cathedral/builder-web/index.phtml',
    'layout/cathedral/builder'    => __DIR__ . '/view/layout/cathedral/builder.phtml',
);
