<?php echo $this->doctype(); ?>
<?php 
$version = \Cathedral\Builder\Version::VERSION;
$version_date = \Cathedral\Builder\Version::VERSION_DATE;
?>
<html lang="en">
<head>
<meta charset="utf-8">
    <?php
    echo $this->headTitle()
        ->prepend('Builder Web UI')
        ->setSeparator(' : ')
        ->setAutoEscape(false);
    
    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    
    // Le styles
    echo $this->headLink()
        ->appendStylesheet('//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css')
        //->appendStylesheet('//code.jquery.com/ui/1.11.2/themes/flick/jquery-ui.css')
    ;
    
    echo $this->headScript()
        ->appendFile('//code.jquery.com/jquery-1.11.0.min.js')
        ->appendFile('//code.jquery.com/ui/1.11.2/jquery-ui.min.js')
    ;
    ?>
    <script type='text/javascript'>
        $(function() {
        	$('.button').button();
            $(document).tooltip();
        });
    </script>
    <style type="text/css">
        body {
            font-family: "Trebuchet MS","Helvetica","Arial","Verdana","sans-serif";
        }
        .small {
        	font-size: 75%;
        }
        .ui-tooltip {
            font-size: 75%;
        }
        .blue {
        	color: blue;
        }
        .red {
        	color: red;
        }
        .orange {
        	color: orange;
        }
        .green {
        	color: green;
        }
        #content {
        	
        }
    </style>
  </head>
<body>
    <div id="content" align="center">
    	<?php 
    	if (\Cathedral\Builder\Version::DEVELOPMENT)
    		echo '<h1>DEVELOPMENT MODE</h1>';
    	?>
    	<?= $this->content ?>
    </div>
    <footer style='padding-top: 20px;'>
        <hr style='width: 60%' />
        <div style="font-size: 70%; text-align: center;">
            Cathedral/Builder: <?=$version?> (<?=$version_date?>)<br />
            <a class='blue' href='https://github.com/CathedralCode/Builder'>Builder on GitHub</a>
        </div>
    </footer>
</body>
</html>
