<?php 
$this->headTitle($this->title);
echo "<h3>$this->title</h3>";

$route = 'builder/build';
$routeParams = ['table' => '0', 'type' => 0];

$tipTables = 'ALL: table data files';
$tipAbstractEntity = 'ALL: abstract entity files';
$tipEntity = 'MISSING ONLY: entity files';
?>
<table>
	<thead>
	<tr>
       <td colspan='4'>Namespace: <strong><?= $this->namespace ?></strong></td>
   </tr>
   <tr>
       <td colspan='4' class='small'>Edit: config/autoload/builderui.global.php to change it.</td>
   </tr>
	<tr>
		<th>table</th>
		<th colspan='3'>generate</th>
	</tr>
	<tr>
		<td>Write All</td>
		<td title='<?=$tipTables?>'><a class='small button blue' href='<?= $this->url($route, $routeParams)?>'>dataTable</a></td>
		<?php $routeParams['type'] = 1; ?>
		<td title='<?=$tipAbstractEntity?>'><a class='small button blue' href='<?= $this->url($route, $routeParams)?>'>entityabstract</a></td>
		<?php $routeParams['type'] = 2; ?>
		<td title='<?=$tipEntity?>'><a class='small button blue' href='<?= $this->url($route, $routeParams)?>'>entity</a></td>
	</tr>
	</thead>
	<tbody>
	<?php
	$bm = $this->builderManager;
	$statusColour=[-1 => 'red', 0 => 'orange', 1 => 'green'];
	
	while ($bm->nextTable()) {
		$table = $bm->getTableName();
		
		$dtc = $statusColour[$bm->existsDataTable()];
		$eac = $statusColour[$bm->existsEntityAbstract()];
		$ec = $statusColour[$bm->existsEntity()];
		
		$routeParams['table'] = $table;
		?>
		<tr>
			<td><?=$table ?></td>
			<?php $routeParams['type'] = 0; ?>
			<td><a class='small button <?=$dtc?>' href='<?= $this->url($route, $routeParams)?>'>dataTable</a></td>
			<?php $routeParams['type'] = 1; ?>
			<td><a class='small button <?=$eac?>' href='<?= $this->url($route, $routeParams)?>'>entityabstract</a></td>
			<?php $routeParams['type'] = 2; ?>
			<td><a class='small button <?=$ec?>' href='<?= $this->url($route, $routeParams)?>'>entity</a></td>
		</tr>
	<?php } ?>
	</tbody>
	<tfoot>
	   <tr>
	       <th colspan='4'>What the colours mean:</th>
	   </tr>
	   <tr>
	       <td class='small'>Green</td>
	       <td colspan='3' class='small green'>File OK</td>
	   </tr>
	   <tr>
	       <td class='small'>Orange</td>
	       <td colspan='3' class='small orange'>Old Version</td>
	   </tr>
	   <tr>
	       <td class='small'>Red</td>
	       <td colspan='3' class='small red'>No File</td>
	   </tr>
	   <tr>
	       <th colspan='4'>Notes:</th>
	   </tr>
	   <tr>
	       <td class='small' valign="top">Entity</td>
	       <td colspan='3' class='small'>Existing Entity files don't get replaced.<br />So you can put any custom/overrides in them.</td>
	   </tr>
	</tfoot>
</table>
