<?php 
$this->headTitle($this->title);
echo "<h3>$this->title</h3>";
?>
<table>
	<thead>
	<tr>
       <td colspan='4' style="font-size: 100%;">Namespace: <strong><?= $this->namespace ?></strong></td>
   </tr>
   <tr>
       <td colspan='4' style="font-size: 75%;">Edit: config/autoload/builderui.global.php to change it.</td>
   </tr>
	<tr>
		<th>table</th>
		<th colspan='3'>generate</th>
	</tr>
	<tr>
		<td>Write All</td>
		<td><a style='color: blue' href='<?= $this->url('builder/default/builder', ['controller' => 'builder', 'action' => 'build', 'table' => '0', 'type' => 0, 'write' => 1])?>'>dataTable</a></td>
		<td><a style='color: blue' href='<?= $this->url('builder/default/builder', ['controller' => 'builder', 'action' => 'build', 'table' => '0', 'type' => 1, 'write' => 1])?>'>entityabstract</a></td>
		<td><a style='color: blue' href='<?= $this->url('builder/default/builder', ['controller' => 'builder', 'action' => 'build', 'table' => '0', 'type' => 2, 'write' => 1])?>'>entity</a></td>
	</tr>
	</thead>
	<tbody>
	<?php
	$bm = $this->builderManager;
	$statusColour=[-1 => 'red', 0 => 'orange', 1 => 'green'];
	
	while ($bm->nextTable()) {
		$table = $bm->getTableName();
		
		$dtc = $statusColour[$bm->existsDataTable()];
		$eac = $statusColour[$bm->existsEntityAbstract()];
		$ec = $statusColour[$bm->existsEntity()];
		
		?>
		<tr>
			<td><?=$table ?></td>
			<td><a style='color: <?=$dtc?>' href='<?= $this->url('builder/default/builder', ['controller' => 'builder', 'action' => 'build', 'table' => $table, 'type' => 0])?>'>dataTable</a></td>
			<td><a style='color: <?=$eac?>' href='<?= $this->url('builder/default/builder', ['controller' => 'builder', 'action' => 'build', 'table' => $table, 'type' => 1])?>'>entityabstract</a></td>
			<td><a style='color: <?=$ec?>' href='<?= $this->url('builder/default/builder', ['controller' => 'builder', 'action' => 'build', 'table' => $table, 'type' => 2])?>'>entity</a></td>
		</tr>
	<?php } ?>
	</tbody>
	<tfoot>
	   <tr>
	       <th colspan='4' style="font-size: 100%;">What the colours mean:</th>
	   </tr>
	   <tr>
	       <td style="font-size: 80%;">Green</td>
	       <td colspan='3' style="font-size: 80%; color:green">File OK</td>
	   </tr>
	   <tr>
	       <td style="font-size: 80%;">Orange</td>
	       <td colspan='3' style="font-size: 80%; color:orange">Old Version</td>
	   </tr>
	   <tr>
	       <td style="font-size: 80%;">Red</td>
	       <td colspan='3' style="font-size: 80%; color:red">No File</td>
	   </tr>
	</tfoot>
</table>
