<?php
$this->headTitle($title);
echo "<h3>{$title}</h3>";
?>

<br />
<div style="clear: both; width: 800px;">
<div align="left">
<table class="ui-widget-header ui-corner-all" style="background-color: #f5f5f5">
	<tr>
		<th width="55px">Table:</th>
		<td width="80px"><?=$table?></td>
		<td class="ui-state-error-text" rowspan="2" width="610px" style="text-align: center;"><?=$saved?></td>
		<td width="135px" style="text-align: right;"><a class='small button' href='<?=$this->url('builder')?>'>Back</a></td>
	</tr>
	<tr>
		<th>Type:</th>
		<td><?=$type?></td>
		<td  style="text-align: right;">
			<a class='small button' href='<?=$this->url('builder/build', ['write' => 1], [], true)?>'>Save</a>
		</td>
	</tr>
</table>
</div>
<pre class="ui-corner-all" style="text-align: left; background-color: #f5f5f5; padding: 15px 15px 15px 15px;"><?=$this->escapeHtml($code)?></pre>
</div>
