<?php echo $this->doctype(); ?>
<?php 
$version = \Cathedral\Builder\Version::VERSION;
$version_date = \Cathedral\Builder\Version::VERSION_DATE;
?>
<html lang="en">
<head>
<meta charset="utf-8">
    <?php
    echo $this->headTitle()
        ->prepend('Builder Basic UI')
        ->setSeparator(' : ')
        ->setAutoEscape(false);
    
    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    
    // Le styles
    echo $this->headLink()
    ->appendStylesheet('//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css')
    ;
    ?>
    <style type="text/css">
        body {
            font-family: "Trebuchet MS","Helvetica","Arial","Verdana","sans-serif";
            
        }
        .btn {
        	font-size: 70%;
        }
    </style>
  </head>
<body>
    <div id="content">
    	<?= $this->content ?>
    </div>
    <footer>
        <div style="font-size: 70%; text-align: center;">Builder: <?=$version?> (<?=$version_date?>)</div>
    </footer>
<?php 
echo $this->headScript()
    ->appendFile('//code.jquery.com/jquery-1.11.0.min.js')
    ->appendFile('//code.jquery.com/ui/1.11.2/jquery-ui.min.js')
;
?>
<script type="text/javascript">
$( "a" ).button();
</script>
</body>
</html>
